# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrowdtanglePreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_preference', models.CharField(max_length=255)),
                ('user_bot_id', models.IntegerField()),
            ],
            options={
                'db_table': 'crowdtangle_preferences',
            },
        ),
    ]
